# deployment type valid values are origin, online, atomic-enterprise,
# and openshift-enterprise
deployment_type: openshift-enterprise

# Specify the generic release of OpenShift to install. This is used mainly just
# during installation, after which we rely on the version running on the first
# master. Works best for containerized installs where we can usually use this
# to lookup the latest exact version of the container images, which is the
# tag actually used to configure the cluster. For RPM installations we just
# verify the version detected in your configured repos matches this release.
openshift_release: v3.6

# Debug level for all OpenShift components (Defaults to 2)
debug_level: 2

# Master API and console ports.
openshift_master_api_port: 443
openshift_master_console_port: 443 

# Use firewalld
os_firewall_use_firewalld: True
