- hosts: masters[0]
  tasks:
  - name: Get storage classes
    command: oc get storageclass -o json
    register: get_storage_classes
    changed_when: false

  - name: Unset default storage class
    command: >-
      oc patch storageclass {{ storageclass.metadata.name | quote }}
      -p {{ patch | to_json | quote }}
    with_items: >-
      {{ get_storage_classes.stdout | from_json | json_query('items') }}
    loop_control:
      loop_var: storageclass
    vars:
      patch:
        metadata:
          annotations:
            storageclass.beta.kubernetes.io/is-default-class: "false" 
    when: >-
      storageclass.metadata.name != my_openshift_default_storageclass and
      storageclass.metadata.annotations is defined and
      storageclass.metadata.annotations["storageclass.beta.kubernetes.io/is-default-class"] is defined and
      storageclass.metadata.annotations["storageclass.beta.kubernetes.io/is-default-class"] == "true"

  - name: Set default storage class
    command: >-
      oc patch storageclass {{ storageclass.metadata.name | quote }}
      -p {{ patch | to_json | quote }}
    with_items: >-
      {{ get_storage_classes.stdout | from_json | json_query('items') }}
    loop_control:
      loop_var: storageclass
    vars:
      patch:
        metadata:
          annotations:
            storageclass.beta.kubernetes.io/is-default-class: "true" 
    when: >-
      storageclass.metadata.name == my_openshift_default_storageclass and (
        storageclass.metadata.annotations is undefined or
        storageclass.metadata.annotations["storageclass.beta.kubernetes.io/is-default-class"] is undefined or
        storageclass.metadata.annotations["storageclass.beta.kubernetes.io/is-default-class"] == "false"
      )
