- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/adhoc/uninstall.yml

- hosts: glusterfs:glusterfs_registry
  tasks:

  - name: Get list of glusterfs volume groups
    shell: >
      vgs | perl -ne 'm/(vg_[0-9a-z]{32})/ and print "$1\n"'
    changed_when: false
    register: get_glusterfs_vgs

  - name: Remove glusterfs volume groups
    command: vgremove --force {{ item }}
    with_items: "{{ get_glusterfs_vgs.stdout_lines }}"

  - name: Wipe signatures from persistent volumes
    command: pvremove --force {{ item }}
    failed_when: false
    with_items: "{{ glusterfs_devices }}"

  - name: Remove glusterfs directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /var/lib/heketi
    - /var/lib/glusterd
    - /var/log/glusterfs

  - name: Recreate empty /var/log/glusterfs
    file:
      path: /var/log/glusterfs
      state: directory
      owner: root
      group: root
      mode: u=rwx,go=rx
